var nome = prompt("Qual é seu nome?");
console.log("Tipo primitivo de nome:",typeof nome);
var anoNascimento = prompt("Qual é a sua data de nascimento dia/mês/ano");
console.log("Tipo primitivo do ano de nascimento:",typeof anoNascimento);
var endereco = prompt("Qual é seu endereço?");
console.log("Tipo primitivo de endereço:",typeof endereco);
var CPF = prompt("Qual é seu CPF?");
console.log("Tipo primitivo de CPF",typeof CPF);
var escolaridade = prompt("Grau de escolaridade: ");
console.log("Tipo primitivo de escolaridade:",typeof escolaridade);
var cnh = prompt("Possui CNH? sim/não");
console.log("Tipo primitivo de cnh:",typeof cnh);
var filhos = prompt("Quantos filhos?");
console.log("Tipo primitivo de filhos:",typeof filhos);
var cargoAtual = prompt("Cargo atual: ");
console.log("Tipo primitivo de cargoAtual:",typeof cargoAtual);
var salario = Number(prompt("Salário:"));
console.log("Tipo primitivo de salario:",typeof salario);
var comissao = Number(prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero."));
console.log("Tipo primitivo de comissao:",typeof comissao);
var anoAdmissao = Number(prompt("Ano de admissão:"));
console.log("Tipo primitivo de anoAdmissao:",typeof anoAdmissao);
console.log("Novo colaborador(a) "+nome+", que nasceu na data "+anoNascimento+". Mora no endereço: "+endereco+". Tem número de CPF: "+CPF+". "+cnh+"tem CNH. Tem",filhos,"filho(s). O cargo que irá ocupar é o de",cargoAtual,"com salário de",salario,"R$ e comissão de "+comissao+"%. O ano de admissão é",anoAdmissao);